#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercicio9.Resource", IsApplication=true)]

namespace Exercicio9
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int btnConfirmar = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int cbxOpcao1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int cbxOpcao2 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int cbxOpcao3 = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int editSenha = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int radioOpcao1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int radioOpcao2 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int radioOpcao3 = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int seekBar1 = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int txtCheckbox = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int txtSenha = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int txtTamanho = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int txtValor = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
