#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercicio5.Resource", IsApplication=true)]

namespace Exercicio5
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int citacoes_gray = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int citacoes_white = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_citacoes = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_mensagens = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_noticias = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_perfil = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int mensagens_gray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mensagens_white = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int noticias_gray = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int noticias_white = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int perfil_gray = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int perfil_white = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
