#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercicio6.Resource", IsApplication=true)]

namespace Exercicio6
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abbeyRoad = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int beatlesForSale = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int hardDaysNight = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int help = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int letItBe = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int magicalMysteryTour = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pleasePleaseMe = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int revolver = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rubberSoul = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sgtPeppers = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int whiteAlbum = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int withTheBeatles = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int yellowSubmarine = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MyButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int application_menu = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int comIcone = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int duasLinhasIguais = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int duasLinhasTitulo = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int textoComCheck = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int textoComCheckBox = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int textoComRadio = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int umaLinha = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int application_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
